INSERT INTO categories (slug, name, emoji) VALUES
  ('food', 'Food & Drinks', '🍕'),
  ('animals', 'Animals', '🐾'),
  ('places', 'Places', '✈️'),
  ('sports', 'Sports & Games', '🏅'),
  ('screen', 'Movies & TV', '🎬'),
  ('professions', 'Professions', '💼'),
  ('objects', 'Household Objects', '🏠'),
  ('music', 'Music', '🎵');

INSERT INTO words (category_id, word, impostor_hint) VALUES
  ((SELECT id FROM categories WHERE slug = 'food'), 'Pizza', 'It comes in slices'),
  ((SELECT id FROM categories WHERE slug = 'food'), 'Sushi', 'Often eaten raw'),
  ((SELECT id FROM categories WHERE slug = 'food'), 'Hamburger', 'Popular fast food'),
  ((SELECT id FROM categories WHERE slug = 'food'), 'Chocolate', 'A sweet treat'),
  ((SELECT id FROM categories WHERE slug = 'food'), 'Coffee', 'A morning ritual'),
  ((SELECT id FROM categories WHERE slug = 'food'), 'Tacos', 'A Mexican favorite'),
  ((SELECT id FROM categories WHERE slug = 'food'), 'Ice cream', 'Best in summer'),
  ((SELECT id FROM categories WHERE slug = 'food'), 'Pasta', 'An Italian staple'),
  ((SELECT id FROM categories WHERE slug = 'food'), 'Pancakes', 'A breakfast classic'),
  ((SELECT id FROM categories WHERE slug = 'food'), 'Cheese', 'Made from milk'),

  ((SELECT id FROM categories WHERE slug = 'animals'), 'Elephant', 'Very heavy'),
  ((SELECT id FROM categories WHERE slug = 'animals'), 'Penguin', 'Lives in the cold'),
  ((SELECT id FROM categories WHERE slug = 'animals'), 'Lion', 'Found in Africa'),
  ((SELECT id FROM categories WHERE slug = 'animals'), 'Dolphin', 'Lives in the ocean'),
  ((SELECT id FROM categories WHERE slug = 'animals'), 'Owl', 'Active at night'),
  ((SELECT id FROM categories WHERE slug = 'animals'), 'Kangaroo', 'From Australia'),
  ((SELECT id FROM categories WHERE slug = 'animals'), 'Snake', 'Has no legs'),
  ((SELECT id FROM categories WHERE slug = 'animals'), 'Spider', 'Many people fear it'),
  ((SELECT id FROM categories WHERE slug = 'animals'), 'Horse', 'People can ride it'),
  ((SELECT id FROM categories WHERE slug = 'animals'), 'Bee', 'Small but busy'),

  ((SELECT id FROM categories WHERE slug = 'places'), 'Beach', 'Great for vacations'),
  ((SELECT id FROM categories WHERE slug = 'places'), 'Airport', 'Lots of waiting'),
  ((SELECT id FROM categories WHERE slug = 'places'), 'Hospital', 'You hope to avoid it'),
  ((SELECT id FROM categories WHERE slug = 'places'), 'Library', 'Keep your voice down'),
  ((SELECT id FROM categories WHERE slug = 'places'), 'Gym', 'People go there to sweat'),
  ((SELECT id FROM categories WHERE slug = 'places'), 'Cinema', 'Dark and crowded'),
  ((SELECT id FROM categories WHERE slug = 'places'), 'Supermarket', 'A weekly visit'),
  ((SELECT id FROM categories WHERE slug = 'places'), 'Museum', 'Full of old things'),
  ((SELECT id FROM categories WHERE slug = 'places'), 'School', 'Kids spend hours here'),
  ((SELECT id FROM categories WHERE slug = 'places'), 'Restaurant', 'Someone serves you here'),

  ((SELECT id FROM categories WHERE slug = 'sports'), 'Soccer', 'The most popular worldwide'),
  ((SELECT id FROM categories WHERE slug = 'sports'), 'Tennis', 'Played with rackets'),
  ((SELECT id FROM categories WHERE slug = 'sports'), 'Basketball', 'Tall players excel at it'),
  ((SELECT id FROM categories WHERE slug = 'sports'), 'Swimming', 'No shoes needed'),
  ((SELECT id FROM categories WHERE slug = 'sports'), 'Boxing', 'One on one'),
  ((SELECT id FROM categories WHERE slug = 'sports'), 'Golf', 'Quiet and slow'),
  ((SELECT id FROM categories WHERE slug = 'sports'), 'Volleyball', 'Also played at the beach'),
  ((SELECT id FROM categories WHERE slug = 'sports'), 'Chess', 'A mind game'),
  ((SELECT id FROM categories WHERE slug = 'sports'), 'Skiing', 'A winter activity'),
  ((SELECT id FROM categories WHERE slug = 'sports'), 'Marathon', 'Takes hours to finish'),

  ((SELECT id FROM categories WHERE slug = 'screen'), 'Titanic', 'Based on real events'),
  ((SELECT id FROM categories WHERE slug = 'screen'), 'Star Wars', 'Set in space'),
  ((SELECT id FROM categories WHERE slug = 'screen'), 'Harry Potter', 'Magic is involved'),
  ((SELECT id FROM categories WHERE slug = 'screen'), 'The Simpsons', 'An animated family'),
  ((SELECT id FROM categories WHERE slug = 'screen'), 'Friends', 'Set in New York'),
  ((SELECT id FROM categories WHERE slug = 'screen'), 'Jurassic Park', 'Creatures from the past'),
  ((SELECT id FROM categories WHERE slug = 'screen'), 'Frozen', 'Kids love it'),
  ((SELECT id FROM categories WHERE slug = 'screen'), 'Batman', 'Has a secret identity'),
  ((SELECT id FROM categories WHERE slug = 'screen'), 'Stranger Things', 'Set in the 80s'),
  ((SELECT id FROM categories WHERE slug = 'screen'), 'The Office', 'A workplace comedy'),

  ((SELECT id FROM categories WHERE slug = 'professions'), 'Doctor', 'Years and years of study'),
  ((SELECT id FROM categories WHERE slug = 'professions'), 'Teacher', 'Works with young people'),
  ((SELECT id FROM categories WHERE slug = 'professions'), 'Firefighter', 'Responds to emergencies'),
  ((SELECT id FROM categories WHERE slug = 'professions'), 'Chef', 'Works with their hands'),
  ((SELECT id FROM categories WHERE slug = 'professions'), 'Pilot', 'Travels constantly'),
  ((SELECT id FROM categories WHERE slug = 'professions'), 'Police officer', 'Wears a uniform'),
  ((SELECT id FROM categories WHERE slug = 'professions'), 'Lawyer', 'Argues for a living'),
  ((SELECT id FROM categories WHERE slug = 'professions'), 'Farmer', 'Works outdoors'),
  ((SELECT id FROM categories WHERE slug = 'professions'), 'Dentist', 'People dread the visit'),
  ((SELECT id FROM categories WHERE slug = 'professions'), 'Programmer', 'Stares at a screen'),

  ((SELECT id FROM categories WHERE slug = 'objects'), 'Refrigerator', 'Found in the kitchen'),
  ((SELECT id FROM categories WHERE slug = 'objects'), 'Television', 'In the living room'),
  ((SELECT id FROM categories WHERE slug = 'objects'), 'Pillow', 'Used every night'),
  ((SELECT id FROM categories WHERE slug = 'objects'), 'Mirror', 'You look at it daily'),
  ((SELECT id FROM categories WHERE slug = 'objects'), 'Umbrella', 'Only used sometimes'),
  ((SELECT id FROM categories WHERE slug = 'objects'), 'Toothbrush', 'Used twice a day'),
  ((SELECT id FROM categories WHERE slug = 'objects'), 'Scissors', 'Handle with care'),
  ((SELECT id FROM categories WHERE slug = 'objects'), 'Candle', 'Sets the mood'),
  ((SELECT id FROM categories WHERE slug = 'objects'), 'Broom', 'For cleaning up'),
  ((SELECT id FROM categories WHERE slug = 'objects'), 'Alarm clock', 'Nobody likes it'),

  ((SELECT id FROM categories WHERE slug = 'music'), 'Guitar', 'It has strings'),
  ((SELECT id FROM categories WHERE slug = 'music'), 'Piano', 'Black and white'),
  ((SELECT id FROM categories WHERE slug = 'music'), 'Drums', 'The loud one'),
  ((SELECT id FROM categories WHERE slug = 'music'), 'Violin', 'A classical favorite'),
  ((SELECT id FROM categories WHERE slug = 'music'), 'Microphone', 'Singers need it'),
  ((SELECT id FROM categories WHERE slug = 'music'), 'Karaoke', 'Fun with friends'),
  ((SELECT id FROM categories WHERE slug = 'music'), 'Opera', 'Very dramatic'),
  ((SELECT id FROM categories WHERE slug = 'music'), 'Concert', 'A live event'),
  ((SELECT id FROM categories WHERE slug = 'music'), 'Headphones', 'For listening alone'),
  ((SELECT id FROM categories WHERE slug = 'music'), 'Trumpet', 'You blow into it');
