-- Seed data in English ('en') and Spanish ('es'). Explicit ids so translation
-- rows can reference them. Word ids: 1-10 food, 11-20 animals, 21-30 places,
-- 31-40 sports, 41-50 screen, 51-60 professions, 61-70 objects, 71-80 music.

INSERT INTO categories (id, slug, emoji) VALUES
  (1, 'food', '🍕'),
  (2, 'animals', '🐾'),
  (3, 'places', '✈️'),
  (4, 'sports', '🏅'),
  (5, 'screen', '🎬'),
  (6, 'professions', '💼'),
  (7, 'objects', '🏠'),
  (8, 'music', '🎵');

INSERT INTO category_translations (category_id, locale, name) VALUES
  (1, 'en', 'Food & Drinks'),        (1, 'es', 'Comida y Bebidas'),
  (2, 'en', 'Animals'),              (2, 'es', 'Animales'),
  (3, 'en', 'Places'),               (3, 'es', 'Lugares'),
  (4, 'en', 'Sports & Games'),       (4, 'es', 'Deportes y Juegos'),
  (5, 'en', 'Movies & TV'),          (5, 'es', 'Cine y TV'),
  (6, 'en', 'Professions'),          (6, 'es', 'Profesiones'),
  (7, 'en', 'Household Objects'),    (7, 'es', 'Objetos del Hogar'),
  (8, 'en', 'Music'),                (8, 'es', 'Música');

INSERT INTO words (id, category_id) VALUES
  (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1),
  (11, 2), (12, 2), (13, 2), (14, 2), (15, 2), (16, 2), (17, 2), (18, 2), (19, 2), (20, 2),
  (21, 3), (22, 3), (23, 3), (24, 3), (25, 3), (26, 3), (27, 3), (28, 3), (29, 3), (30, 3),
  (31, 4), (32, 4), (33, 4), (34, 4), (35, 4), (36, 4), (37, 4), (38, 4), (39, 4), (40, 4),
  (41, 5), (42, 5), (43, 5), (44, 5), (45, 5), (46, 5), (47, 5), (48, 5), (49, 5), (50, 5),
  (51, 6), (52, 6), (53, 6), (54, 6), (55, 6), (56, 6), (57, 6), (58, 6), (59, 6), (60, 6),
  (61, 7), (62, 7), (63, 7), (64, 7), (65, 7), (66, 7), (67, 7), (68, 7), (69, 7), (70, 7),
  (71, 8), (72, 8), (73, 8), (74, 8), (75, 8), (76, 8), (77, 8), (78, 8), (79, 8), (80, 8);

INSERT INTO word_translations (word_id, locale, word, impostor_hint) VALUES
  -- Food & Drinks
  (1, 'en', 'Pizza', 'It comes in slices'),
  (1, 'es', 'Pizza', 'Viene en porciones'),
  (2, 'en', 'Sushi', 'Often eaten raw'),
  (2, 'es', 'Sushi', 'A menudo se come crudo'),
  (3, 'en', 'Hamburger', 'Popular fast food'),
  (3, 'es', 'Hamburguesa', 'Comida rápida popular'),
  (4, 'en', 'Chocolate', 'A sweet treat'),
  (4, 'es', 'Chocolate', 'Un gusto dulce'),
  (5, 'en', 'Coffee', 'A morning ritual'),
  (5, 'es', 'Café', 'Un ritual matutino'),
  (6, 'en', 'Tacos', 'A Mexican favorite'),
  (6, 'es', 'Tacos', 'Un favorito mexicano'),
  (7, 'en', 'Ice cream', 'Best in summer'),
  (7, 'es', 'Helado', 'Mejor en verano'),
  (8, 'en', 'Pasta', 'An Italian staple'),
  (8, 'es', 'Pasta', 'Un clásico italiano'),
  (9, 'en', 'Pancakes', 'A breakfast classic'),
  (9, 'es', 'Panqueques', 'Un clásico del desayuno'),
  (10, 'en', 'Cheese', 'Made from milk'),
  (10, 'es', 'Queso', 'Hecho de leche'),

  -- Animals
  (11, 'en', 'Elephant', 'Very heavy'),
  (11, 'es', 'Elefante', 'Muy pesado'),
  (12, 'en', 'Penguin', 'Lives in the cold'),
  (12, 'es', 'Pingüino', 'Vive en el frío'),
  (13, 'en', 'Lion', 'Found in Africa'),
  (13, 'es', 'León', 'Se encuentra en África'),
  (14, 'en', 'Dolphin', 'Lives in the ocean'),
  (14, 'es', 'Delfín', 'Vive en el océano'),
  (15, 'en', 'Owl', 'Active at night'),
  (15, 'es', 'Búho', 'Activo de noche'),
  (16, 'en', 'Kangaroo', 'From Australia'),
  (16, 'es', 'Canguro', 'Viene de Australia'),
  (17, 'en', 'Snake', 'Has no legs'),
  (17, 'es', 'Serpiente', 'No tiene patas'),
  (18, 'en', 'Spider', 'Many people fear it'),
  (18, 'es', 'Araña', 'Mucha gente le teme'),
  (19, 'en', 'Horse', 'People can ride it'),
  (19, 'es', 'Caballo', 'La gente puede montarlo'),
  (20, 'en', 'Bee', 'Small but busy'),
  (20, 'es', 'Abeja', 'Pequeña pero muy ocupada'),

  -- Places
  (21, 'en', 'Beach', 'Great for vacations'),
  (21, 'es', 'Playa', 'Ideal para vacaciones'),
  (22, 'en', 'Airport', 'Lots of waiting'),
  (22, 'es', 'Aeropuerto', 'Mucha espera'),
  (23, 'en', 'Hospital', 'You hope to avoid it'),
  (23, 'es', 'Hospital', 'Esperas no tener que ir'),
  (24, 'en', 'Library', 'Keep your voice down'),
  (24, 'es', 'Biblioteca', 'Baja la voz'),
  (25, 'en', 'Gym', 'People go there to sweat'),
  (25, 'es', 'Gimnasio', 'La gente va a sudar'),
  (26, 'en', 'Cinema', 'Dark and crowded'),
  (26, 'es', 'Cine', 'Oscuro y lleno de gente'),
  (27, 'en', 'Supermarket', 'A weekly visit'),
  (27, 'es', 'Supermercado', 'Una visita semanal'),
  (28, 'en', 'Museum', 'Full of old things'),
  (28, 'es', 'Museo', 'Lleno de cosas antiguas'),
  (29, 'en', 'School', 'Kids spend hours here'),
  (29, 'es', 'Escuela', 'Los niños pasan horas aquí'),
  (30, 'en', 'Restaurant', 'Someone serves you here'),
  (30, 'es', 'Restaurante', 'Aquí te atienden'),

  -- Sports & Games
  (31, 'en', 'Soccer', 'The most popular worldwide'),
  (31, 'es', 'Fútbol', 'El más popular del mundo'),
  (32, 'en', 'Tennis', 'Played with rackets'),
  (32, 'es', 'Tenis', 'Se juega con raquetas'),
  (33, 'en', 'Basketball', 'Tall players excel at it'),
  (33, 'es', 'Básquetbol', 'Los altos se destacan'),
  (34, 'en', 'Swimming', 'No shoes needed'),
  (34, 'es', 'Natación', 'No se necesitan zapatos'),
  (35, 'en', 'Boxing', 'One on one'),
  (35, 'es', 'Boxeo', 'Uno contra uno'),
  (36, 'en', 'Golf', 'Quiet and slow'),
  (36, 'es', 'Golf', 'Tranquilo y lento'),
  (37, 'en', 'Volleyball', 'Also played at the beach'),
  (37, 'es', 'Vóleibol', 'También se juega en la playa'),
  (38, 'en', 'Chess', 'A mind game'),
  (38, 'es', 'Ajedrez', 'Un juego mental'),
  (39, 'en', 'Skiing', 'A winter activity'),
  (39, 'es', 'Esquí', 'Una actividad de invierno'),
  (40, 'en', 'Marathon', 'Takes hours to finish'),
  (40, 'es', 'Maratón', 'Toma horas terminarla'),

  -- Movies & TV
  (41, 'en', 'Titanic', 'Based on real events'),
  (41, 'es', 'Titanic', 'Basada en hechos reales'),
  (42, 'en', 'Star Wars', 'Set in space'),
  (42, 'es', 'Star Wars', 'Ambientada en el espacio'),
  (43, 'en', 'Harry Potter', 'Magic is involved'),
  (43, 'es', 'Harry Potter', 'Hay magia de por medio'),
  (44, 'en', 'The Simpsons', 'An animated family'),
  (44, 'es', 'Los Simpson', 'Una familia animada'),
  (45, 'en', 'Friends', 'Set in New York'),
  (45, 'es', 'Friends', 'Ambientada en Nueva York'),
  (46, 'en', 'Jurassic Park', 'Creatures from the past'),
  (46, 'es', 'Jurassic Park', 'Criaturas del pasado'),
  (47, 'en', 'Frozen', 'Kids love it'),
  (47, 'es', 'Frozen', 'A los niños les encanta'),
  (48, 'en', 'Batman', 'Has a secret identity'),
  (48, 'es', 'Batman', 'Tiene una identidad secreta'),
  (49, 'en', 'Stranger Things', 'Set in the 80s'),
  (49, 'es', 'Stranger Things', 'Ambientada en los 80'),
  (50, 'en', 'The Office', 'A workplace comedy'),
  (50, 'es', 'The Office', 'Una comedia de oficina'),

  -- Professions
  (51, 'en', 'Doctor', 'Years and years of study'),
  (51, 'es', 'Médico', 'Años y años de estudio'),
  (52, 'en', 'Teacher', 'Works with young people'),
  (52, 'es', 'Maestro', 'Trabaja con jóvenes'),
  (53, 'en', 'Firefighter', 'Responds to emergencies'),
  (53, 'es', 'Bombero', 'Responde a emergencias'),
  (54, 'en', 'Chef', 'Works with their hands'),
  (54, 'es', 'Chef', 'Trabaja con las manos'),
  (55, 'en', 'Pilot', 'Travels constantly'),
  (55, 'es', 'Piloto', 'Viaja constantemente'),
  (56, 'en', 'Police officer', 'Wears a uniform'),
  (56, 'es', 'Policía', 'Usa uniforme'),
  (57, 'en', 'Lawyer', 'Argues for a living'),
  (57, 'es', 'Abogado', 'Discute para ganarse la vida'),
  (58, 'en', 'Farmer', 'Works outdoors'),
  (58, 'es', 'Agricultor', 'Trabaja al aire libre'),
  (59, 'en', 'Dentist', 'People dread the visit'),
  (59, 'es', 'Dentista', 'La gente teme la visita'),
  (60, 'en', 'Programmer', 'Stares at a screen'),
  (60, 'es', 'Programador', 'Mira una pantalla todo el día'),

  -- Household Objects
  (61, 'en', 'Refrigerator', 'Found in the kitchen'),
  (61, 'es', 'Refrigerador', 'Está en la cocina'),
  (62, 'en', 'Television', 'In the living room'),
  (62, 'es', 'Televisor', 'Está en la sala'),
  (63, 'en', 'Pillow', 'Used every night'),
  (63, 'es', 'Almohada', 'Se usa cada noche'),
  (64, 'en', 'Mirror', 'You look at it daily'),
  (64, 'es', 'Espejo', 'Lo miras a diario'),
  (65, 'en', 'Umbrella', 'Only used sometimes'),
  (65, 'es', 'Paraguas', 'Solo se usa a veces'),
  (66, 'en', 'Toothbrush', 'Used twice a day'),
  (66, 'es', 'Cepillo de dientes', 'Se usa dos veces al día'),
  (67, 'en', 'Scissors', 'Handle with care'),
  (67, 'es', 'Tijeras', 'Manejar con cuidado'),
  (68, 'en', 'Candle', 'Sets the mood'),
  (68, 'es', 'Vela', 'Crea ambiente'),
  (69, 'en', 'Broom', 'For cleaning up'),
  (69, 'es', 'Escoba', 'Sirve para limpiar'),
  (70, 'en', 'Alarm clock', 'Nobody likes it'),
  (70, 'es', 'Despertador', 'A nadie le gusta'),

  -- Music
  (71, 'en', 'Guitar', 'It has strings'),
  (71, 'es', 'Guitarra', 'Tiene cuerdas'),
  (72, 'en', 'Piano', 'Black and white'),
  (72, 'es', 'Piano', 'Blanco y negro'),
  (73, 'en', 'Drums', 'The loud one'),
  (73, 'es', 'Batería', 'La más ruidosa'),
  (74, 'en', 'Violin', 'A classical favorite'),
  (74, 'es', 'Violín', 'Un favorito de la música clásica'),
  (75, 'en', 'Microphone', 'Singers need it'),
  (75, 'es', 'Micrófono', 'Los cantantes lo necesitan'),
  (76, 'en', 'Karaoke', 'Fun with friends'),
  (76, 'es', 'Karaoke', 'Diversión con amigos'),
  (77, 'en', 'Opera', 'Very dramatic'),
  (77, 'es', 'Ópera', 'Muy dramática'),
  (78, 'en', 'Concert', 'A live event'),
  (78, 'es', 'Concierto', 'Un evento en vivo'),
  (79, 'en', 'Headphones', 'For listening alone'),
  (79, 'es', 'Auriculares', 'Para escuchar a solas'),
  (80, 'en', 'Trumpet', 'You blow into it'),
  (80, 'es', 'Trompeta', 'Se sopla');
